---
driver:
  name: docker
platforms:
  - name: almalinux-8
    image: almalinux:8
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
  # - name: almalinux-9
  #   image: almalinux:9
  #   dockerfile: ../common/Dockerfile.j2
  #   privileged: true
  #   cgroupns_mode: host
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   command: /usr/sbin/init
  # - name: rockylinux-8
  #   image: rockylinux:8
  #   dockerfile: ../common/Dockerfile.j2
  #   privileged: true
  #   cgroupns_mode: host
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   command: /usr/sbin/init
  # - name: rockylinux-9
  #   image: rockylinux:9.0
  #   dockerfile: ../common/Dockerfile.j2
  #   privileged: true
  #   cgroupns_mode: host
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   command: /usr/sbin/init
  # - name: debian-bullseye
  #   image: debian:bullseye-slim
  #   dockerfile: ../common/Dockerfile.j2
  #   privileged: true
  #   cgroupns_mode: host
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   command: /sbin/init
  # - name: debian-bookworm
  #   image: debian:bookworm-slim
  #   dockerfile: ../common/Dockerfile.j2
  #   privileged: true
  #   cgroupns_mode: host
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   command: /sbin/init
  # - name: ubuntu-focal
  #   image: ubuntu:focal
  #   dockerfile: ../common/Dockerfile.j2
  #   privileged: true
  #   cgroupns_mode: host
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   command: /sbin/init
  # - name: ubuntu-jammy
  #   image: ubuntu:jammy
  #   dockerfile: ../common/Dockerfile.j2
  #   privileged: true
  #   cgroupns_mode: host
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   command: /sbin/init
  # - name: ubuntu-noble
  #   image: ubuntu:noble
  #   dockerfile: ../common/Dockerfile.j2
  #   privileged: true
  #   cgroupns_mode: host
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   command: /sbin/init
  # - name: ubuntu-oracular
  #   image: ubuntu:oracular
  #   dockerfile: ../common/Dockerfile.j2
  #   privileged: true
  #   cgroupns_mode: host
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   command: /sbin/init
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      interpreter_python: auto_silent
  playbooks:
    converge: converge.yml
  inventory:
    host_vars:
      almalinux-8:
        ansible_python_interpreter: /usr/libexec/platform-python
  env:
    ANSIBLE_ROLES_PATH: ~/.cache/molecule/ansible-role-nginx/${MOLECULE_SCENARIO_NAME}/roles:${MOLECULE_PROJECT_DIRECTORY}/..:~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
verifier:
  name: testinfra