---
base_packages_list:
- vim
- wget
- python3-pip
- git
- fail2ban
- chrony
- rsyslog

base_debian_packages_list:
  - lsb-release
  - apt-transport-https
  - ca-certificates
  - ufw

base_redhat_packages_list:
  - yum-utils
  - firewalld
  - fail2ban-firewalld
