---
base_debian_package_list:
  - lsb-release
  - apt-transport-https
  - ca-certificates
  - vim
  - wget
  - curl
  - ufw
  - python3-pip
  - git
  - iptables-persistent
  - fail2ban

base_redhat_package_list:
  - epel-release
  - git 
  - yum-utils
  - firewalld
  - vim
  - wget
  - python3-pip
  - fail2ban
