---
- name: Allow nginx to connect to upstream
  ansible.builtin.command: setsebool -P httpd_can_network_connect 1
  changed_when: false
  become: true
  when:
    - ansible_facts.selinux is defined
    - ansible_facts.selinux.status is defined
    - ansible_facts.selinux.status == "enabled"

