---
- name: Converge
  hosts: all
  vars:
    vhost: example.kz
  tasks:
    - name: Nginx Role
      ansible.builtin.include_role:
        name: nginx

    - name: Django Role
      ansible.builtin.include_role:
        name: django
