---
- name: restart debian php-fpm
  service:
    name: php{{ php_default_version }}-fpm
    state: restarted
    enabled: true

- name: restart centos php-fpm
  service:
    name: php{{ php_default_version_short }}-php-fpm
    state: restarted
    enabled: true

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
