---
# PHP Versioning
php_default_version_short: 83           # Used in legacy module naming (e.g., php83-php-*)
php_default_version: 8.3        # Used in modern module naming (e.g., php8.3-* style)

php_apt_repo_gpg_key: "https://mirror.ps.kz/sury/packages.sury.org/php/apt.gpg"
php_sury_repo: >-
  deb https://packages.sury.org/php {{ ansible_facts['distribution_release'] }} main

php_debian_packages:
  - php{{ php_default_version }}-common
  - php{{ php_default_version }}-cli
  - php{{ php_default_version }}-dev
  - libpcre3-dev
  - php{{ php_default_version }}-gd
  - php{{ php_default_version }}-curl
  - php{{ php_default_version }}-imap
  - php{{ php_default_version }}-opcache
  - php{{ php_default_version }}-xml
  - php{{ php_default_version }}-mbstring
  - php{{ php_default_version }}-apcu
  - php{{ php_default_version }}-sqlite3
  - php{{ php_default_version }}-dom
  - php{{ php_default_version }}-dev
  - php{{ php_default_version }}-intl
  - php{{ php_default_version }}-mysql
  - php{{ php_default_version }}-zip
  - php{{ php_default_version }}-soap
  - php{{ php_default_version }}-imagick
  - php{{ php_default_version }}-pdo

php_redhat_packages:
  - php{{ php_default_version_short }}-php-common
  - php{{ php_default_version_short }}-php-cli
  - php{{ php_default_version_short }}-php-devel
  - pcre-devel
  - php{{ php_default_version_short }}-php-gd
  - php{{ php_default_version_short }}-php-curl
  - php{{ php_default_version_short }}-php-imap
  - php{{ php_default_version_short }}-php-opcache
  - php{{ php_default_version_short }}-php-xml
  - php{{ php_default_version_short }}-php-mbstring
  - php{{ php_default_version_short }}-php-apcu
  - php{{ php_default_version_short }}-php-sqlite3
  - php{{ php_default_version_short }}-php-dom
  - php{{ php_default_version_short }}-php-intl
  - php{{ php_default_version_short }}-php-mysql
  - php{{ php_default_version_short }}-php-zip
  - php{{ php_default_version_short }}-php-soap
  - php{{ php_default_version_short }}-php-imagick
  - php{{ php_default_version_short }}-php-pdo
